apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster
data:
  AUTH_PORT: "8001"
  FLAG_PORT: "8002"
  TARGETING_PORT: "8003"
  EVALUATION_PORT: "8004"
  ANALYTICS_PORT: "8005"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  AWS_REGION: "us-east-1"
  DYNAMODB_TABLE: "ToggleMasterAnalytics"
