apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: togglemaster
  namespace: argocd
spec:
  description: ToggleMaster feature-flag platform
  sourceRepos:
    - '*'
  destinations:
    - namespace: togglemaster
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
